## Copyright 2022 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

dependencies:
  - name: azure-cli
    version: "2.23"
    download-link-windows: 
    download-link-linux:
    modules:
    - name: azure-cli-ext-azure-devops
      version: "0.21"
  - name: git
    version: "2"
    download-link-windows: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.gz
    download-link-linux:
    checksums: 
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.sign
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.xz
source:
  - instanceName: azure-building-blocks
    repo: https://github.com/AgileCloudInstitute/azure-building-blocks.git
    branch: dev
  - instanceName: acm-system-templates
    repo: https://github.com/AgileCloudInstitute/acm-system-templates.git
    branch: main
